### ISSUE TITLE
MongoDB : "To udpate this DocumentEntity the field `id` is required"

### ISSUE THREAD

**Issue by lmorel3** [eclipse/jnosql-diana-driver#101]
Hi,

I'm trying to use the "save()" method of my entity repository, but I'm facing an issue. 
Indeed, I chose to use a custom column name for the **id** of my Entity, but when one call the save method, it throws an exception: "To udpate this DocumentEntity the field `id` is required". 

Then, I cheked the class [MongoDBDocumentCollectionManager](https://github.com/eclipse/jnosql-diana-driver/blob/master/mongodb-driver/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentCollectionManager.java) and the constant "ID_FIELD" is statictly set to "_id".  So, I think here is the issue. 

Moreover, when I insert data, a "_id" is always generated but it might be the MongoDB behavior.

My @Entity class
```
    @Id("id")
    private String id;
```

Btw, I chose to rename this column because when I tried to use "repo.findById()", it never worked using the value of "_id"... Now, it works with "id" value. 

Hope you have a solution :)

**Comment by otaviojava** [comment]
Hey, could you give us more information?
What version are you using?

I tried the new version, 0.0.6.

```java
@Entity
public class Animal {

    @Id
    private String id;

    @Column
    private String name;

    Animal() {
    }

    Animal(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Animal{");
        sb.append("id='").append(id).append('\'');
        sb.append(", name='").append(name).append('\'');
        sb.append('}');
        return sb.toString();
    }
}
```

## The repository

```java
public interface AnimalRepository extends Repository<Animal, String> {
}
```
The App

```java
public class AnimalApp {

    public static void main(String[] args) {
        try (SeContainer container = SeContainerInitializer.newInstance().initialize()) {
            AnimalRepository repository = container.select(AnimalRepository.class, DatabaseQualifier.ofDocument()).get();

            String id = "lion";
            Animal animal = new Animal(id, "Lion");
            repository.save(animal);
            Optional<Animal> lion = repository.findById(id);
            System.out.println(lion);
            animal = new Animal(id, "Lion Updated");
            repository.save(animal);
            lion = repository.findById(id);
            repository.deleteById(id);
            lion = repository.findById(id);
            System.out.println(lion);
        }
    }
}

```

## The output


```
save (will create)Optional[Animal{id='lion', name='Lion'}]
save (will update)Optional[Animal{id='lion', name='Lion Updated'}]
save (will empty)Optional.empty
jul 31, 2018 4:37:24 AM org.jboss.weld.environment.se.WeldContainer shutdown
INFO: WELD-ENV-002001: Weld SE container 0b8adfb7-5535-4571-acee-71ce4d9f8680 shut down
```

**Comment by otaviojava** [comment]
btw: Thank you for the feedback

**Comment by lmorel3** [comment]
I switched to 0.0.6 because I was using 0.0.5. I also remove the `@Id("id")` for `@Id` only.
But it didn't worked. 

In fact I tried to use the MongoDB generated id, but it's sth like "ObjectId("....")", not directly the value of the id. So I have to generate a unique id manually.

Now, I can fetch the project, but I cannot update it.
Here is the whole stacktrace.
```
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy298.save(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.eclipse.projectpartners.repositories.ProjectRepository$169634186$Proxy$_$$_WeldClientProxy.save(Unknown Source)
	at org.eclipse.projectpartners.services.PartnerService.addTags(PartnerService.java:57)
	at org.eclipse.projectpartners.services.PartnerService$Proxy$_$$_WeldClientProxy.addTags(Unknown Source)
	at org.eclipse.projectpartners.rest.PartnerResource.addTags(PartnerResource.java:30)
	at org.eclipse.projectpartners.rest.PartnerResource$Proxy$_$$_WeldClientProxy.addTags(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:704)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jnosql.artemis.document.query.AbstractDocumentRepositoryProxy.invoke(AbstractDocumentRepositoryProxy.java:71)
	... 66 more
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class org.jnosql.diana.api.document.DefaultDocument.
	at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
	at org.bson.codecs.configuration.ChildCodecRegistry.get(ChildCodecRegistry.java:51)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:184)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:207)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:180)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:207)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:180)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:199)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:182)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:207)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:180)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:199)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:141)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:136)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:115)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:41)
	at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:238)
	at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:188)
	at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:129)
	at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:138)
	at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:236)
	at com.mongodb.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:98)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:441)
	at com.mongodb.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:70)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:192)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:264)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.operation.CommandOperationHelper$3.call(CommandOperationHelper.java:436)
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:433)
	at com.mongodb.operation.CommandOperationHelper.executeRetryableCommand(CommandOperationHelper.java:429)
	at com.mongodb.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:33)
	at com.mongodb.operation.FindAndReplaceOperation.execute(FindAndReplaceOperation.java:56)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:155)
	at com.mongodb.client.internal.MongoCollectionImpl.executeFindOneAndReplace(MongoCollectionImpl.java:650)
	at com.mongodb.client.internal.MongoCollectionImpl.findOneAndReplace(MongoCollectionImpl.java:633)
	at com.mongodb.client.internal.MongoCollectionImpl.findOneAndReplace(MongoCollectionImpl.java:628)
	at org.jnosql.diana.mongodb.document.MongoDBDocumentCollectionManager.update(MongoDBDocumentCollectionManager.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.jnosql.diana.api.document.AutoCloseable$DocumentCollectionManager$691849609$Proxy$_$$_WeldClientProxy.update(Unknown Source)
	at org.jnosql.artemis.document.AbstractDocumentTemplate.lambda$new$1(AbstractDocumentTemplate.java:68)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.jnosql.artemis.document.AbsctractDocumentWorkflow.flow(AbsctractDocumentWorkflow.java:39)
	at org.jnosql.artemis.document.AbstractDocumentTemplate.update(AbstractDocumentTemplate.java:99)
	at org.jnosql.artemis.document.query.AbstractDocumentRepository.save(AbstractDocumentRepository.java:52)
	... 71 more
```

Thanks for your time

**Comment by lmorel3** [comment]
To simplify, I've designed my current data model.

![Data Model](https://user-images.githubusercontent.com/1393808/43464410-5a6119e4-94db-11e8-8db4-db79aa3b0c41.jpg)

As you can see, there's 3 levels of embedded documents. It might be the beginning of the issue... :)

**Comment by otaviojava** [comment]
Nice, do you mind if you send me the classes?
With the annotations, everything?

**Comment by lmorel3** [comment]
I just gave you access to my git repo. Thanks!

Le mar. 31 juil. 2018 à 17:20, Otávio Santana <notifications@github.com> a
écrit :

**Comment by otaviojava** [comment]
Please, keep the Id annotation without overriding the value.
Could you try the version 0.0.7-snapshot?

Change the version and also add the repository in the pom.xml as this code: 
```xml
<repositories>
	        <repository>
	            <id>snapshots-repo</id>
	            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
	            <releases>
	                <enabled>false</enabled>
	            </releases>
	            <snapshots>
	                <enabled>true</enabled>
	            </snapshots>
	        </repository>
	    </repositories>
```
Like this: https://github.com/eldermoraes/javaee-nosql/blob/master/careerbuddy/pom.xml
Ps: One crucial information is when an Entity is as a Field that will work as the subdocument concept. The Embeddable works as JPA does. Maybe try to put @Entity at Partner and Address.

**Comment by lmorel3** [comment]
Does that mean I can directly findById a "Partner" for example? Which could be great, because for now it returns the whole "Project" and then I've to filter etc. :)

Anyway, the 0.0.7-SNAPSHOT doesn't exist on (Sonatype repo)[https://oss.sonatype.org/content/repositories/snapshots/org/jnosql/diana/mongodb-driver/]

I'm trying with @Entity annotations and 0.0.6-SNAPSHOT (the latest available).

**Comment by otaviojava** [comment]
Hey Sorry, maybe an issue with my internet.
Please, refresh it again.
About query you have the option to execute a "native" query:

## Given

```java
Project project = new Project();
project.setId("id");
project.setName("project");
 List<Partner> partners = new ArrayList<>();
Partner partner = new Partner();
partner.setCountry("Brazil");
 partner.setRole("role");
  partner.setName("name");
 Address address = new Address();
 address.setCountry("Brazil");
  address.setLatitude(12D);
  address.setLongitude(10D);
 address.setNumber("number");
 partner.setLocation(address);
  partners.add(partner);
  project.setPartners(partners);
```
```java
 Optional<Project> result = documentTemplate.singleResult(query);
 System.out.println("query by Brazil" + result);
```
Also using the **DocumentQueryMapperBuilder** that will translate the query to you using the annotations:

```java
@Inject
DocumentQueryMapperBuilder builder;
```

```java
DocumentQuery query = builder.selectFrom(Project.class).where("partners.country").eq("Brazil").build();
Optional<Project> result = documentTemplate.singleResult(query);
System.out.println("query by Brazil " + result);
```

**Comment by lmorel3** [comment]
Thanks Otavio, 0.0.7-SNAPSHOT works well.

But I still have the issue when I'm trying to save a Project if one of its Partner has a "Tag" (reminder: A Project contains x Partner and a Partner has n Tag(s))

Concerning the query, I already use raw query like this one and it works well. I was just wondering if we can return a "Partner" and not the whole project but I think its not possible. :)

**Comment by lmorel3** [comment]
Well, I tried to append tags manually in DB. Now, when I try to call "findAll()" method, it throws an exception: 

```
java.lang.ClassCastException: org.bson.Document cannot be cast to java.util.List
```

This should be the issue. And I also tried to use a List<String> instead of a List<Tag> but same thing happens! :)

**Comment by otaviojava** [comment]
Yes, that was a bug, could you remove the mongodb driver, locally, to download the newest version again?

```java
@Entity
public class Tag {

    @Column
    private String id;
    
    @Column
    private String name;
```
```java
@Entity
public class Partner {
....
   @Column
    private List<Tag> tags;
....

}
```

```java

    Project project = new Project();
        Tag tag = new Tag();
        tag.setId("java");
        tag.setName("Java");
        Tag tag2 = new Tag();
        tag2.setId("nosql");
        tag2.setName("Nosql");

        project.setId("id");
        project.setName("project");
        List<Partner> partners = new ArrayList<>();
        Partner partner = new Partner();
        partner.setCountry("Brazil");
        partner.setRole("role");
        partner.setName("name");
        partner.setType("type");
        Address address = new Address();
        address.setCountry("Brazil");
        address.setStreet("street");
        address.setLatitude(12D);
        address.setLongitude(10D);
        address.setNumber("number");
        partner.setLocation(address);
        partner.setTags(Arrays.asList(tag, tag2));
        partners.add(partner);
        project.setPartners(partners);

```

```java
 DocumentQuery query = builder.selectFrom(Project.class).where("partners.tags.id").eq("java").build();
 Optional<Project> result = documentTemplate.singleResult(query);
 System.out.println("query by tag java " + result);
```

**Comment by lmorel3** [comment]
Thanks for you answer. So, I should keep the 0.0.7-SNAPSHOT? 

Perhaps, I've this maven error: 
```
Could not resolve dependencies for project partners-service:partners-service:war:1.0-SNAPSHOT: Failure to find **org.jnosql.query:jnosql-query-antlr:jar:0.0.7-SNAPSHOT** in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of snapshots-repo has elapsed or updates are forced
```

How does the "snapshot" release cycle works?

**Comment by otaviojava** [comment]
Could you go to your maven local and remove the folder: **jnosql** at Maven_HOME/repository/org

**Comment by lmorel3** [comment]
That's what I did but I retried by removing both jnosql and mongodb from my Maven local cache and ... everything works perfectly! 

Thanks you for your time, because I was totally stuck with this issue :)

**Comment by otaviojava** [comment]
:)
you welcome @lmorel3 
If there are more issues, please, let me know.
For now, I'll close this one, however, feel free to open it again.
