### ISSUE TITLE
Test library in production code

### ISSUE THREAD

**Issue by vepo** [eclipse/jnosql-diana-driver#110]
Mongo Drive includes a test library as compile dependency. 

```
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>${flapdoodle.embed.mongo}</version>
        </dependency>
```

This causes an exception:
```
Caused by: java.lang.NoSuchMethodError: com.mongodb.internal.operation.SyncOperations.<init>(Lcom/mongodb/MongoNamespace;Ljava/lang/Class;Lcom/mongodb/ReadPreference;Lorg/bson/codecs/configuration/CodecRegistry;Lcom/mongodb/WriteConcern;ZLcom/mongodb/ReadConcern;)V
	at com.mongodb.client.internal.MongoCollectionImpl.<init>(MongoCollectionImpl.java:101)
	at com.mongodb.client.internal.MongoDatabaseImpl.getCollection(MongoDatabaseImpl.java:126)
	at com.mongodb.client.internal.MongoDatabaseImpl.getCollection(MongoDatabaseImpl.java:121)
```

**Comment by otaviojava** [comment]
Hey, thank you for the feedback.
Fixed in: https://github.com/eclipse/jnosql-diana-driver/pull/111
