### ISSUE TITLE
Update JaCoCo Library

### ISSUE THREAD

**Issue by KyleAure** [eclipse/jnosql-diana-driver#148]
It looks like we are currently using JaCoCo 0.7.9.  But there is a known issue with this version that is resolved after release 0.8.0 here (https://github.com/jacoco/jacoco/issues/551).  

This results in the following error when running `mvn clean install` on all driver builds if you are using jdk 11+:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project cassandra-driver: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/kyleaure/git/jnosql-diana-driver/cassandra-driver/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/kyleaure/git/jnosql-diana-driver/cassandra-driver && /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home/bin/java -javaagent:/Users/kyleaure/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/kyleaure/git/jnosql-diana-driver/target/jacoco.exec,append=true -jar /Users/kyleaure/git/jnosql-diana-driver/cassandra-driver/target/surefire/surefirebooter943056064844347810.jar /Users/kyleaure/git/jnosql-diana-driver/cassandra-driver/target/surefire 2019-10-09T10-36-20_028-jvmRun1 surefire9520213770837676774tmp surefire_04904413122198380525tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 87
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

When investigating the cause we see the same exception as that raised in the JaCoCo issue: 
```
...
# Created at 2019-10-09T10:36:20.652
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
# Created at 2019-10-09T10:36:20.652
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
# Created at 2019-10-09T10:36:20.652
	at org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
# Created at 2019-10-09T10:36:20.652
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)
# Created at 2019-10-09T10:36:20.653
	at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)
# Created at 2019-10-09T10:36:20.653
	... 6 more
# Created at 2019-10-09T10:36:20.653
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
...
```

**Comment by otaviojava** [comment]
@KyleAure thank you, we can check to update this version.
Did you try to update the version and run the tests?
https://github.com/eclipse-ee4j/nosql/blob/master/pom.xml#L58

**Comment by KyleAure** [comment]
Yes, I tried updating the version locally and tests ran normally.  I see a PR https://github.com/eclipse-ee4j/nosql/pull/29 updated the version to 0.8.4.  I will go ahead and close this issue.
